// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStockAssistantAPI creates a new StockAssistant instance
func NewStockAssistantAPI(spec *loads.Document) *StockAssistantAPI {
	return &StockAssistantAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		UserIndexAddHandler: UserIndexAddHandlerFunc(func(params UserIndexAddParams) middleware.Responder {
			return middleware.NotImplemented("operation UserIndexAdd has not yet been implemented")
		}),
		UserIndexDeleteHandler: UserIndexDeleteHandlerFunc(func(params UserIndexDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation UserIndexDelete has not yet been implemented")
		}),
		UserIndexGetHandler: UserIndexGetHandlerFunc(func(params UserIndexGetParams) middleware.Responder {
			return middleware.NotImplemented("operation UserIndexGet has not yet been implemented")
		}),
		UserIndexListHandler: UserIndexListHandlerFunc(func(params UserIndexListParams) middleware.Responder {
			return middleware.NotImplemented("operation UserIndexList has not yet been implemented")
		}),
		UserIndexUpdateHandler: UserIndexUpdateHandlerFunc(func(params UserIndexUpdateParams) middleware.Responder {
			return middleware.NotImplemented("operation UserIndexUpdate has not yet been implemented")
		}),
		UserSettingsAddHandler: UserSettingsAddHandlerFunc(func(params UserSettingsAddParams) middleware.Responder {
			return middleware.NotImplemented("operation UserSettingsAdd has not yet been implemented")
		}),
		UserSettingsDeleteHandler: UserSettingsDeleteHandlerFunc(func(params UserSettingsDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation UserSettingsDelete has not yet been implemented")
		}),
		UserSettingsGetHandler: UserSettingsGetHandlerFunc(func(params UserSettingsGetParams) middleware.Responder {
			return middleware.NotImplemented("operation UserSettingsGet has not yet been implemented")
		}),
		UserSettingsListHandler: UserSettingsListHandlerFunc(func(params UserSettingsListParams) middleware.Responder {
			return middleware.NotImplemented("operation UserSettingsList has not yet been implemented")
		}),
		UserSettingsUpdateHandler: UserSettingsUpdateHandlerFunc(func(params UserSettingsUpdateParams) middleware.Responder {
			return middleware.NotImplemented("operation UserSettingsUpdate has not yet been implemented")
		}),
		UserStockEvaluateAddOrUpdateHandler: UserStockEvaluateAddOrUpdateHandlerFunc(func(params UserStockEvaluateAddOrUpdateParams) middleware.Responder {
			return middleware.NotImplemented("operation UserStockEvaluateAddOrUpdate has not yet been implemented")
		}),
		UserStockEvaluateGetHandler: UserStockEvaluateGetHandlerFunc(func(params UserStockEvaluateGetParams) middleware.Responder {
			return middleware.NotImplemented("operation UserStockEvaluateGet has not yet been implemented")
		}),
		UserStockEvaluateListHandler: UserStockEvaluateListHandlerFunc(func(params UserStockEvaluateListParams) middleware.Responder {
			return middleware.NotImplemented("operation UserStockEvaluateList has not yet been implemented")
		}),
	}
}

/*StockAssistantAPI the stock assistant API */
type StockAssistantAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json;charset=utf-8" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json;charset=utf-8" mime type
	JSONProducer runtime.Producer

	// UserIndexAddHandler sets the operation handler for the user index add operation
	UserIndexAddHandler UserIndexAddHandler
	// UserIndexDeleteHandler sets the operation handler for the user index delete operation
	UserIndexDeleteHandler UserIndexDeleteHandler
	// UserIndexGetHandler sets the operation handler for the user index get operation
	UserIndexGetHandler UserIndexGetHandler
	// UserIndexListHandler sets the operation handler for the user index list operation
	UserIndexListHandler UserIndexListHandler
	// UserIndexUpdateHandler sets the operation handler for the user index update operation
	UserIndexUpdateHandler UserIndexUpdateHandler
	// UserSettingsAddHandler sets the operation handler for the user settings add operation
	UserSettingsAddHandler UserSettingsAddHandler
	// UserSettingsDeleteHandler sets the operation handler for the user settings delete operation
	UserSettingsDeleteHandler UserSettingsDeleteHandler
	// UserSettingsGetHandler sets the operation handler for the user settings get operation
	UserSettingsGetHandler UserSettingsGetHandler
	// UserSettingsListHandler sets the operation handler for the user settings list operation
	UserSettingsListHandler UserSettingsListHandler
	// UserSettingsUpdateHandler sets the operation handler for the user settings update operation
	UserSettingsUpdateHandler UserSettingsUpdateHandler
	// UserStockEvaluateAddOrUpdateHandler sets the operation handler for the user stock evaluate add or update operation
	UserStockEvaluateAddOrUpdateHandler UserStockEvaluateAddOrUpdateHandler
	// UserStockEvaluateGetHandler sets the operation handler for the user stock evaluate get operation
	UserStockEvaluateGetHandler UserStockEvaluateGetHandler
	// UserStockEvaluateListHandler sets the operation handler for the user stock evaluate list operation
	UserStockEvaluateListHandler UserStockEvaluateListHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *StockAssistantAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *StockAssistantAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *StockAssistantAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *StockAssistantAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *StockAssistantAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *StockAssistantAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *StockAssistantAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the StockAssistantAPI
func (o *StockAssistantAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.UserIndexAddHandler == nil {
		unregistered = append(unregistered, "UserIndexAddHandler")
	}

	if o.UserIndexDeleteHandler == nil {
		unregistered = append(unregistered, "UserIndexDeleteHandler")
	}

	if o.UserIndexGetHandler == nil {
		unregistered = append(unregistered, "UserIndexGetHandler")
	}

	if o.UserIndexListHandler == nil {
		unregistered = append(unregistered, "UserIndexListHandler")
	}

	if o.UserIndexUpdateHandler == nil {
		unregistered = append(unregistered, "UserIndexUpdateHandler")
	}

	if o.UserSettingsAddHandler == nil {
		unregistered = append(unregistered, "UserSettingsAddHandler")
	}

	if o.UserSettingsDeleteHandler == nil {
		unregistered = append(unregistered, "UserSettingsDeleteHandler")
	}

	if o.UserSettingsGetHandler == nil {
		unregistered = append(unregistered, "UserSettingsGetHandler")
	}

	if o.UserSettingsListHandler == nil {
		unregistered = append(unregistered, "UserSettingsListHandler")
	}

	if o.UserSettingsUpdateHandler == nil {
		unregistered = append(unregistered, "UserSettingsUpdateHandler")
	}

	if o.UserStockEvaluateAddOrUpdateHandler == nil {
		unregistered = append(unregistered, "UserStockEvaluateAddOrUpdateHandler")
	}

	if o.UserStockEvaluateGetHandler == nil {
		unregistered = append(unregistered, "UserStockEvaluateGetHandler")
	}

	if o.UserStockEvaluateListHandler == nil {
		unregistered = append(unregistered, "UserStockEvaluateListHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *StockAssistantAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *StockAssistantAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *StockAssistantAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *StockAssistantAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *StockAssistantAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *StockAssistantAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the stock assistant API
func (o *StockAssistantAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *StockAssistantAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/{userId}/indices"] = NewUserIndexAdd(o.context, o.UserIndexAddHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/{userId}/indices/{indexId}"] = NewUserIndexDelete(o.context, o.UserIndexDeleteHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/indices/{indexId}"] = NewUserIndexGet(o.context, o.UserIndexGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/indices"] = NewUserIndexList(o.context, o.UserIndexListHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/{userId}/indices/{indexId}"] = NewUserIndexUpdate(o.context, o.UserIndexUpdateHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/{userId}/settings"] = NewUserSettingsAdd(o.context, o.UserSettingsAddHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/{userId}/settings/{configKey}"] = NewUserSettingsDelete(o.context, o.UserSettingsDeleteHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/settings/{configKey}"] = NewUserSettingsGet(o.context, o.UserSettingsGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/settings"] = NewUserSettingsList(o.context, o.UserSettingsListHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/{userId}/settings/{configKey}"] = NewUserSettingsUpdate(o.context, o.UserSettingsUpdateHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/{userId}/stockEvaluates/{stockId}"] = NewUserStockEvaluateAddOrUpdate(o.context, o.UserStockEvaluateAddOrUpdateHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/stockEvaluates/{stockId}"] = NewUserStockEvaluateGet(o.context, o.UserStockEvaluateGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{userId}/stockEvaluates"] = NewUserStockEvaluateList(o.context, o.UserStockEvaluateListHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *StockAssistantAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *StockAssistantAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
