// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserIndexGetOKCode is the HTTP code returned for type UserIndexGetOK
const UserIndexGetOKCode int = 200

/*UserIndexGetOK ok

swagger:response userIndexGetOK
*/
type UserIndexGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.StockIndex `json:"body,omitempty"`
}

// NewUserIndexGetOK creates UserIndexGetOK with default headers values
func NewUserIndexGetOK() *UserIndexGetOK {
	return &UserIndexGetOK{}
}

// WithPayload adds the payload to the user index get o k response
func (o *UserIndexGetOK) WithPayload(payload *models.StockIndex) *UserIndexGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index get o k response
func (o *UserIndexGetOK) SetPayload(payload *models.StockIndex) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserIndexGetBadRequestCode is the HTTP code returned for type UserIndexGetBadRequest
const UserIndexGetBadRequestCode int = 400

/*UserIndexGetBadRequest Bad request

swagger:response userIndexGetBadRequest
*/
type UserIndexGetBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexGetBadRequest creates UserIndexGetBadRequest with default headers values
func NewUserIndexGetBadRequest() *UserIndexGetBadRequest {
	return &UserIndexGetBadRequest{}
}

// WithPayload adds the payload to the user index get bad request response
func (o *UserIndexGetBadRequest) WithPayload(payload string) *UserIndexGetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index get bad request response
func (o *UserIndexGetBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserIndexGetInternalServerErrorCode is the HTTP code returned for type UserIndexGetInternalServerError
const UserIndexGetInternalServerErrorCode int = 500

/*UserIndexGetInternalServerError Internal error

swagger:response userIndexGetInternalServerError
*/
type UserIndexGetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexGetInternalServerError creates UserIndexGetInternalServerError with default headers values
func NewUserIndexGetInternalServerError() *UserIndexGetInternalServerError {
	return &UserIndexGetInternalServerError{}
}

// WithPayload adds the payload to the user index get internal server error response
func (o *UserIndexGetInternalServerError) WithPayload(payload string) *UserIndexGetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index get internal server error response
func (o *UserIndexGetInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexGetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
