// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UserSettingsDeleteOKCode is the HTTP code returned for type UserSettingsDeleteOK
const UserSettingsDeleteOKCode int = 200

/*UserSettingsDeleteOK ok

swagger:response userSettingsDeleteOK
*/
type UserSettingsDeleteOK struct {
}

// NewUserSettingsDeleteOK creates UserSettingsDeleteOK with default headers values
func NewUserSettingsDeleteOK() *UserSettingsDeleteOK {
	return &UserSettingsDeleteOK{}
}

// WriteResponse to the client
func (o *UserSettingsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// UserSettingsDeleteBadRequestCode is the HTTP code returned for type UserSettingsDeleteBadRequest
const UserSettingsDeleteBadRequestCode int = 400

/*UserSettingsDeleteBadRequest Bad request

swagger:response userSettingsDeleteBadRequest
*/
type UserSettingsDeleteBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsDeleteBadRequest creates UserSettingsDeleteBadRequest with default headers values
func NewUserSettingsDeleteBadRequest() *UserSettingsDeleteBadRequest {
	return &UserSettingsDeleteBadRequest{}
}

// WithPayload adds the payload to the user settings delete bad request response
func (o *UserSettingsDeleteBadRequest) WithPayload(payload string) *UserSettingsDeleteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings delete bad request response
func (o *UserSettingsDeleteBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsDeleteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserSettingsDeleteInternalServerErrorCode is the HTTP code returned for type UserSettingsDeleteInternalServerError
const UserSettingsDeleteInternalServerErrorCode int = 500

/*UserSettingsDeleteInternalServerError Internal error

swagger:response userSettingsDeleteInternalServerError
*/
type UserSettingsDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsDeleteInternalServerError creates UserSettingsDeleteInternalServerError with default headers values
func NewUserSettingsDeleteInternalServerError() *UserSettingsDeleteInternalServerError {
	return &UserSettingsDeleteInternalServerError{}
}

// WithPayload adds the payload to the user settings delete internal server error response
func (o *UserSettingsDeleteInternalServerError) WithPayload(payload string) *UserSettingsDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings delete internal server error response
func (o *UserSettingsDeleteInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
