// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserIndexAddOKCode is the HTTP code returned for type UserIndexAddOK
const UserIndexAddOKCode int = 200

/*UserIndexAddOK ok

swagger:response userIndexAddOK
*/
type UserIndexAddOK struct {

	/*
	  In: Body
	*/
	Payload *models.StockIndex `json:"body,omitempty"`
}

// NewUserIndexAddOK creates UserIndexAddOK with default headers values
func NewUserIndexAddOK() *UserIndexAddOK {
	return &UserIndexAddOK{}
}

// WithPayload adds the payload to the user index add o k response
func (o *UserIndexAddOK) WithPayload(payload *models.StockIndex) *UserIndexAddOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index add o k response
func (o *UserIndexAddOK) SetPayload(payload *models.StockIndex) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexAddOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserIndexAddBadRequestCode is the HTTP code returned for type UserIndexAddBadRequest
const UserIndexAddBadRequestCode int = 400

/*UserIndexAddBadRequest Bad request

swagger:response userIndexAddBadRequest
*/
type UserIndexAddBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexAddBadRequest creates UserIndexAddBadRequest with default headers values
func NewUserIndexAddBadRequest() *UserIndexAddBadRequest {
	return &UserIndexAddBadRequest{}
}

// WithPayload adds the payload to the user index add bad request response
func (o *UserIndexAddBadRequest) WithPayload(payload string) *UserIndexAddBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index add bad request response
func (o *UserIndexAddBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexAddBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserIndexAddInternalServerErrorCode is the HTTP code returned for type UserIndexAddInternalServerError
const UserIndexAddInternalServerErrorCode int = 500

/*UserIndexAddInternalServerError Internal error

swagger:response userIndexAddInternalServerError
*/
type UserIndexAddInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexAddInternalServerError creates UserIndexAddInternalServerError with default headers values
func NewUserIndexAddInternalServerError() *UserIndexAddInternalServerError {
	return &UserIndexAddInternalServerError{}
}

// WithPayload adds the payload to the user index add internal server error response
func (o *UserIndexAddInternalServerError) WithPayload(payload string) *UserIndexAddInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index add internal server error response
func (o *UserIndexAddInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexAddInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
