// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserStockEvaluateAddOrUpdateHandlerFunc turns a function with the right signature into a user stock evaluate add or update handler
type UserStockEvaluateAddOrUpdateHandlerFunc func(UserStockEvaluateAddOrUpdateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserStockEvaluateAddOrUpdateHandlerFunc) Handle(params UserStockEvaluateAddOrUpdateParams) middleware.Responder {
	return fn(params)
}

// UserStockEvaluateAddOrUpdateHandler interface for that can handle valid user stock evaluate add or update params
type UserStockEvaluateAddOrUpdateHandler interface {
	Handle(UserStockEvaluateAddOrUpdateParams) middleware.Responder
}

// NewUserStockEvaluateAddOrUpdate creates a new http.Handler for the user stock evaluate add or update operation
func NewUserStockEvaluateAddOrUpdate(ctx *middleware.Context, handler UserStockEvaluateAddOrUpdateHandler) *UserStockEvaluateAddOrUpdate {
	return &UserStockEvaluateAddOrUpdate{Context: ctx, Handler: handler}
}

/*UserStockEvaluateAddOrUpdate swagger:route POST /{userId}/stockEvaluates/{stockId} userStockEvaluateAddOrUpdate

add or update

*/
type UserStockEvaluateAddOrUpdate struct {
	Context *middleware.Context
	Handler UserStockEvaluateAddOrUpdateHandler
}

func (o *UserStockEvaluateAddOrUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserStockEvaluateAddOrUpdateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
