// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserIndexListHandlerFunc turns a function with the right signature into a user index list handler
type UserIndexListHandlerFunc func(UserIndexListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserIndexListHandlerFunc) Handle(params UserIndexListParams) middleware.Responder {
	return fn(params)
}

// UserIndexListHandler interface for that can handle valid user index list params
type UserIndexListHandler interface {
	Handle(UserIndexListParams) middleware.Responder
}

// NewUserIndexList creates a new http.Handler for the user index list operation
func NewUserIndexList(ctx *middleware.Context, handler UserIndexListHandler) *UserIndexList {
	return &UserIndexList{Context: ctx, Handler: handler}
}

/*UserIndexList swagger:route GET /{userId}/indices userIndexList

Get user indices

*/
type UserIndexList struct {
	Context *middleware.Context
	Handler UserIndexListHandler
}

func (o *UserIndexList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserIndexListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
