// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserIndexListOKCode is the HTTP code returned for type UserIndexListOK
const UserIndexListOKCode int = 200

/*UserIndexListOK ok

swagger:response userIndexListOK
*/
type UserIndexListOK struct {

	/*
	  In: Body
	*/
	Payload models.UserIndexListOKBody `json:"body,omitempty"`
}

// NewUserIndexListOK creates UserIndexListOK with default headers values
func NewUserIndexListOK() *UserIndexListOK {
	return &UserIndexListOK{}
}

// WithPayload adds the payload to the user index list o k response
func (o *UserIndexListOK) WithPayload(payload models.UserIndexListOKBody) *UserIndexListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index list o k response
func (o *UserIndexListOK) SetPayload(payload models.UserIndexListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.UserIndexListOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserIndexListBadRequestCode is the HTTP code returned for type UserIndexListBadRequest
const UserIndexListBadRequestCode int = 400

/*UserIndexListBadRequest Bad request

swagger:response userIndexListBadRequest
*/
type UserIndexListBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexListBadRequest creates UserIndexListBadRequest with default headers values
func NewUserIndexListBadRequest() *UserIndexListBadRequest {
	return &UserIndexListBadRequest{}
}

// WithPayload adds the payload to the user index list bad request response
func (o *UserIndexListBadRequest) WithPayload(payload string) *UserIndexListBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index list bad request response
func (o *UserIndexListBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserIndexListInternalServerErrorCode is the HTTP code returned for type UserIndexListInternalServerError
const UserIndexListInternalServerErrorCode int = 500

/*UserIndexListInternalServerError Internal error

swagger:response userIndexListInternalServerError
*/
type UserIndexListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexListInternalServerError creates UserIndexListInternalServerError with default headers values
func NewUserIndexListInternalServerError() *UserIndexListInternalServerError {
	return &UserIndexListInternalServerError{}
}

// WithPayload adds the payload to the user index list internal server error response
func (o *UserIndexListInternalServerError) WithPayload(payload string) *UserIndexListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index list internal server error response
func (o *UserIndexListInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
