// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserSettingsGetOKCode is the HTTP code returned for type UserSettingsGetOK
const UserSettingsGetOKCode int = 200

/*UserSettingsGetOK ok

swagger:response userSettingsGetOK
*/
type UserSettingsGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Setting `json:"body,omitempty"`
}

// NewUserSettingsGetOK creates UserSettingsGetOK with default headers values
func NewUserSettingsGetOK() *UserSettingsGetOK {
	return &UserSettingsGetOK{}
}

// WithPayload adds the payload to the user settings get o k response
func (o *UserSettingsGetOK) WithPayload(payload *models.Setting) *UserSettingsGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings get o k response
func (o *UserSettingsGetOK) SetPayload(payload *models.Setting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserSettingsGetBadRequestCode is the HTTP code returned for type UserSettingsGetBadRequest
const UserSettingsGetBadRequestCode int = 400

/*UserSettingsGetBadRequest Bad request

swagger:response userSettingsGetBadRequest
*/
type UserSettingsGetBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsGetBadRequest creates UserSettingsGetBadRequest with default headers values
func NewUserSettingsGetBadRequest() *UserSettingsGetBadRequest {
	return &UserSettingsGetBadRequest{}
}

// WithPayload adds the payload to the user settings get bad request response
func (o *UserSettingsGetBadRequest) WithPayload(payload string) *UserSettingsGetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings get bad request response
func (o *UserSettingsGetBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserSettingsGetInternalServerErrorCode is the HTTP code returned for type UserSettingsGetInternalServerError
const UserSettingsGetInternalServerErrorCode int = 500

/*UserSettingsGetInternalServerError Internal error

swagger:response userSettingsGetInternalServerError
*/
type UserSettingsGetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsGetInternalServerError creates UserSettingsGetInternalServerError with default headers values
func NewUserSettingsGetInternalServerError() *UserSettingsGetInternalServerError {
	return &UserSettingsGetInternalServerError{}
}

// WithPayload adds the payload to the user settings get internal server error response
func (o *UserSettingsGetInternalServerError) WithPayload(payload string) *UserSettingsGetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings get internal server error response
func (o *UserSettingsGetInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsGetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
