// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserIndexAddHandlerFunc turns a function with the right signature into a user index add handler
type UserIndexAddHandlerFunc func(UserIndexAddParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserIndexAddHandlerFunc) Handle(params UserIndexAddParams) middleware.Responder {
	return fn(params)
}

// UserIndexAddHandler interface for that can handle valid user index add params
type UserIndexAddHandler interface {
	Handle(UserIndexAddParams) middleware.Responder
}

// NewUserIndexAdd creates a new http.Handler for the user index add operation
func NewUserIndexAdd(ctx *middleware.Context, handler UserIndexAddHandler) *UserIndexAdd {
	return &UserIndexAdd{Context: ctx, Handler: handler}
}

/*UserIndexAdd swagger:route PUT /{userId}/indices userIndexAdd

User add new index

*/
type UserIndexAdd struct {
	Context *middleware.Context
	Handler UserIndexAddHandler
}

func (o *UserIndexAdd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserIndexAddParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
