// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserSettingsListHandlerFunc turns a function with the right signature into a user settings list handler
type UserSettingsListHandlerFunc func(UserSettingsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserSettingsListHandlerFunc) Handle(params UserSettingsListParams) middleware.Responder {
	return fn(params)
}

// UserSettingsListHandler interface for that can handle valid user settings list params
type UserSettingsListHandler interface {
	Handle(UserSettingsListParams) middleware.Responder
}

// NewUserSettingsList creates a new http.Handler for the user settings list operation
func NewUserSettingsList(ctx *middleware.Context, handler UserSettingsListHandler) *UserSettingsList {
	return &UserSettingsList{Context: ctx, Handler: handler}
}

/*UserSettingsList swagger:route GET /{userId}/settings userSettingsList

list

*/
type UserSettingsList struct {
	Context *middleware.Context
	Handler UserSettingsListHandler
}

func (o *UserSettingsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserSettingsListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
