// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UserIndexDeleteOKCode is the HTTP code returned for type UserIndexDeleteOK
const UserIndexDeleteOKCode int = 200

/*UserIndexDeleteOK ok

swagger:response userIndexDeleteOK
*/
type UserIndexDeleteOK struct {
}

// NewUserIndexDeleteOK creates UserIndexDeleteOK with default headers values
func NewUserIndexDeleteOK() *UserIndexDeleteOK {
	return &UserIndexDeleteOK{}
}

// WriteResponse to the client
func (o *UserIndexDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// UserIndexDeleteBadRequestCode is the HTTP code returned for type UserIndexDeleteBadRequest
const UserIndexDeleteBadRequestCode int = 400

/*UserIndexDeleteBadRequest Bad request

swagger:response userIndexDeleteBadRequest
*/
type UserIndexDeleteBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexDeleteBadRequest creates UserIndexDeleteBadRequest with default headers values
func NewUserIndexDeleteBadRequest() *UserIndexDeleteBadRequest {
	return &UserIndexDeleteBadRequest{}
}

// WithPayload adds the payload to the user index delete bad request response
func (o *UserIndexDeleteBadRequest) WithPayload(payload string) *UserIndexDeleteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index delete bad request response
func (o *UserIndexDeleteBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexDeleteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserIndexDeleteInternalServerErrorCode is the HTTP code returned for type UserIndexDeleteInternalServerError
const UserIndexDeleteInternalServerErrorCode int = 500

/*UserIndexDeleteInternalServerError Internal error

swagger:response userIndexDeleteInternalServerError
*/
type UserIndexDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserIndexDeleteInternalServerError creates UserIndexDeleteInternalServerError with default headers values
func NewUserIndexDeleteInternalServerError() *UserIndexDeleteInternalServerError {
	return &UserIndexDeleteInternalServerError{}
}

// WithPayload adds the payload to the user index delete internal server error response
func (o *UserIndexDeleteInternalServerError) WithPayload(payload string) *UserIndexDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user index delete internal server error response
func (o *UserIndexDeleteInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserIndexDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
