// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserSettingsAddOKCode is the HTTP code returned for type UserSettingsAddOK
const UserSettingsAddOKCode int = 200

/*UserSettingsAddOK ok

swagger:response userSettingsAddOK
*/
type UserSettingsAddOK struct {

	/*
	  In: Body
	*/
	Payload *models.Setting `json:"body,omitempty"`
}

// NewUserSettingsAddOK creates UserSettingsAddOK with default headers values
func NewUserSettingsAddOK() *UserSettingsAddOK {
	return &UserSettingsAddOK{}
}

// WithPayload adds the payload to the user settings add o k response
func (o *UserSettingsAddOK) WithPayload(payload *models.Setting) *UserSettingsAddOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings add o k response
func (o *UserSettingsAddOK) SetPayload(payload *models.Setting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsAddOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserSettingsAddBadRequestCode is the HTTP code returned for type UserSettingsAddBadRequest
const UserSettingsAddBadRequestCode int = 400

/*UserSettingsAddBadRequest Bad request

swagger:response userSettingsAddBadRequest
*/
type UserSettingsAddBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsAddBadRequest creates UserSettingsAddBadRequest with default headers values
func NewUserSettingsAddBadRequest() *UserSettingsAddBadRequest {
	return &UserSettingsAddBadRequest{}
}

// WithPayload adds the payload to the user settings add bad request response
func (o *UserSettingsAddBadRequest) WithPayload(payload string) *UserSettingsAddBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings add bad request response
func (o *UserSettingsAddBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsAddBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UserSettingsAddInternalServerErrorCode is the HTTP code returned for type UserSettingsAddInternalServerError
const UserSettingsAddInternalServerErrorCode int = 500

/*UserSettingsAddInternalServerError Internal error

swagger:response userSettingsAddInternalServerError
*/
type UserSettingsAddInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserSettingsAddInternalServerError creates UserSettingsAddInternalServerError with default headers values
func NewUserSettingsAddInternalServerError() *UserSettingsAddInternalServerError {
	return &UserSettingsAddInternalServerError{}
}

// WithPayload adds the payload to the user settings add internal server error response
func (o *UserSettingsAddInternalServerError) WithPayload(payload string) *UserSettingsAddInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user settings add internal server error response
func (o *UserSettingsAddInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserSettingsAddInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
