// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// NewUserStockEvaluateAddOrUpdateParams creates a new UserStockEvaluateAddOrUpdateParams object
// with the default values initialized.
func NewUserStockEvaluateAddOrUpdateParams() *UserStockEvaluateAddOrUpdateParams {
	var ()
	return &UserStockEvaluateAddOrUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserStockEvaluateAddOrUpdateParamsWithTimeout creates a new UserStockEvaluateAddOrUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserStockEvaluateAddOrUpdateParamsWithTimeout(timeout time.Duration) *UserStockEvaluateAddOrUpdateParams {
	var ()
	return &UserStockEvaluateAddOrUpdateParams{

		timeout: timeout,
	}
}

// NewUserStockEvaluateAddOrUpdateParamsWithContext creates a new UserStockEvaluateAddOrUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserStockEvaluateAddOrUpdateParamsWithContext(ctx context.Context) *UserStockEvaluateAddOrUpdateParams {
	var ()
	return &UserStockEvaluateAddOrUpdateParams{

		Context: ctx,
	}
}

// NewUserStockEvaluateAddOrUpdateParamsWithHTTPClient creates a new UserStockEvaluateAddOrUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserStockEvaluateAddOrUpdateParamsWithHTTPClient(client *http.Client) *UserStockEvaluateAddOrUpdateParams {
	var ()
	return &UserStockEvaluateAddOrUpdateParams{
		HTTPClient: client,
	}
}

/*UserStockEvaluateAddOrUpdateParams contains all the parameters to send to the API endpoint
for the user stock evaluate add or update operation typically these are written to a http.Request
*/
type UserStockEvaluateAddOrUpdateParams struct {

	/*StockEvaluate*/
	StockEvaluate *models.StockEvaluate
	/*StockID
	  stock id

	*/
	StockID string
	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithTimeout(timeout time.Duration) *UserStockEvaluateAddOrUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithContext(ctx context.Context) *UserStockEvaluateAddOrUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithHTTPClient(client *http.Client) *UserStockEvaluateAddOrUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStockEvaluate adds the stockEvaluate to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithStockEvaluate(stockEvaluate *models.StockEvaluate) *UserStockEvaluateAddOrUpdateParams {
	o.SetStockEvaluate(stockEvaluate)
	return o
}

// SetStockEvaluate adds the stockEvaluate to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetStockEvaluate(stockEvaluate *models.StockEvaluate) {
	o.StockEvaluate = stockEvaluate
}

// WithStockID adds the stockID to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithStockID(stockID string) *UserStockEvaluateAddOrUpdateParams {
	o.SetStockID(stockID)
	return o
}

// SetStockID adds the stockId to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetStockID(stockID string) {
	o.StockID = stockID
}

// WithUserID adds the userID to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) WithUserID(userID string) *UserStockEvaluateAddOrUpdateParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user stock evaluate add or update params
func (o *UserStockEvaluateAddOrUpdateParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserStockEvaluateAddOrUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.StockEvaluate == nil {
		o.StockEvaluate = new(models.StockEvaluate)
	}

	if err := r.SetBodyParam(o.StockEvaluate); err != nil {
		return err
	}

	// path param stockId
	if err := r.SetPathParam("stockId", o.StockID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
