// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// NewUserIndexAddParams creates a new UserIndexAddParams object
// with the default values initialized.
func NewUserIndexAddParams() *UserIndexAddParams {
	var ()
	return &UserIndexAddParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserIndexAddParamsWithTimeout creates a new UserIndexAddParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserIndexAddParamsWithTimeout(timeout time.Duration) *UserIndexAddParams {
	var ()
	return &UserIndexAddParams{

		timeout: timeout,
	}
}

// NewUserIndexAddParamsWithContext creates a new UserIndexAddParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserIndexAddParamsWithContext(ctx context.Context) *UserIndexAddParams {
	var ()
	return &UserIndexAddParams{

		Context: ctx,
	}
}

// NewUserIndexAddParamsWithHTTPClient creates a new UserIndexAddParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserIndexAddParamsWithHTTPClient(client *http.Client) *UserIndexAddParams {
	var ()
	return &UserIndexAddParams{
		HTTPClient: client,
	}
}

/*UserIndexAddParams contains all the parameters to send to the API endpoint
for the user index add operation typically these are written to a http.Request
*/
type UserIndexAddParams struct {

	/*Index
	  Index

	*/
	Index *models.StockIndex
	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user index add params
func (o *UserIndexAddParams) WithTimeout(timeout time.Duration) *UserIndexAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user index add params
func (o *UserIndexAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user index add params
func (o *UserIndexAddParams) WithContext(ctx context.Context) *UserIndexAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user index add params
func (o *UserIndexAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user index add params
func (o *UserIndexAddParams) WithHTTPClient(client *http.Client) *UserIndexAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user index add params
func (o *UserIndexAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIndex adds the index to the user index add params
func (o *UserIndexAddParams) WithIndex(index *models.StockIndex) *UserIndexAddParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the user index add params
func (o *UserIndexAddParams) SetIndex(index *models.StockIndex) {
	o.Index = index
}

// WithUserID adds the userID to the user index add params
func (o *UserIndexAddParams) WithUserID(userID string) *UserIndexAddParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user index add params
func (o *UserIndexAddParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserIndexAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Index == nil {
		o.Index = new(models.StockIndex)
	}

	if err := r.SetBodyParam(o.Index); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
