// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// NewUserSettingsAddParams creates a new UserSettingsAddParams object
// with the default values initialized.
func NewUserSettingsAddParams() *UserSettingsAddParams {
	var ()
	return &UserSettingsAddParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserSettingsAddParamsWithTimeout creates a new UserSettingsAddParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserSettingsAddParamsWithTimeout(timeout time.Duration) *UserSettingsAddParams {
	var ()
	return &UserSettingsAddParams{

		timeout: timeout,
	}
}

// NewUserSettingsAddParamsWithContext creates a new UserSettingsAddParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserSettingsAddParamsWithContext(ctx context.Context) *UserSettingsAddParams {
	var ()
	return &UserSettingsAddParams{

		Context: ctx,
	}
}

// NewUserSettingsAddParamsWithHTTPClient creates a new UserSettingsAddParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserSettingsAddParamsWithHTTPClient(client *http.Client) *UserSettingsAddParams {
	var ()
	return &UserSettingsAddParams{
		HTTPClient: client,
	}
}

/*UserSettingsAddParams contains all the parameters to send to the API endpoint
for the user settings add operation typically these are written to a http.Request
*/
type UserSettingsAddParams struct {

	/*Setting
	  setting

	*/
	Setting *models.Setting
	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user settings add params
func (o *UserSettingsAddParams) WithTimeout(timeout time.Duration) *UserSettingsAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user settings add params
func (o *UserSettingsAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user settings add params
func (o *UserSettingsAddParams) WithContext(ctx context.Context) *UserSettingsAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user settings add params
func (o *UserSettingsAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user settings add params
func (o *UserSettingsAddParams) WithHTTPClient(client *http.Client) *UserSettingsAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user settings add params
func (o *UserSettingsAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSetting adds the setting to the user settings add params
func (o *UserSettingsAddParams) WithSetting(setting *models.Setting) *UserSettingsAddParams {
	o.SetSetting(setting)
	return o
}

// SetSetting adds the setting to the user settings add params
func (o *UserSettingsAddParams) SetSetting(setting *models.Setting) {
	o.Setting = setting
}

// WithUserID adds the userID to the user settings add params
func (o *UserSettingsAddParams) WithUserID(userID string) *UserSettingsAddParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user settings add params
func (o *UserSettingsAddParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserSettingsAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Setting == nil {
		o.Setting = new(models.Setting)
	}

	if err := r.SetBodyParam(o.Setting); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
