// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserStockEvaluateListReader is a Reader for the UserStockEvaluateList structure.
type UserStockEvaluateListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserStockEvaluateListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserStockEvaluateListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserStockEvaluateListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUserStockEvaluateListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserStockEvaluateListOK creates a UserStockEvaluateListOK with default headers values
func NewUserStockEvaluateListOK() *UserStockEvaluateListOK {
	return &UserStockEvaluateListOK{}
}

/*UserStockEvaluateListOK handles this case with default header values.

ok
*/
type UserStockEvaluateListOK struct {
	Payload models.UserStockEvaluateListOKBody
}

func (o *UserStockEvaluateListOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/stockEvaluates][%d] userStockEvaluateListOK  %+v", 200, o.Payload)
}

func (o *UserStockEvaluateListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserStockEvaluateListBadRequest creates a UserStockEvaluateListBadRequest with default headers values
func NewUserStockEvaluateListBadRequest() *UserStockEvaluateListBadRequest {
	return &UserStockEvaluateListBadRequest{}
}

/*UserStockEvaluateListBadRequest handles this case with default header values.

Bad request
*/
type UserStockEvaluateListBadRequest struct {
	Payload string
}

func (o *UserStockEvaluateListBadRequest) Error() string {
	return fmt.Sprintf("[GET /{userId}/stockEvaluates][%d] userStockEvaluateListBadRequest  %+v", 400, o.Payload)
}

func (o *UserStockEvaluateListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserStockEvaluateListInternalServerError creates a UserStockEvaluateListInternalServerError with default headers values
func NewUserStockEvaluateListInternalServerError() *UserStockEvaluateListInternalServerError {
	return &UserStockEvaluateListInternalServerError{}
}

/*UserStockEvaluateListInternalServerError handles this case with default header values.

Internal error
*/
type UserStockEvaluateListInternalServerError struct {
	Payload string
}

func (o *UserStockEvaluateListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{userId}/stockEvaluates][%d] userStockEvaluateListInternalServerError  %+v", 500, o.Payload)
}

func (o *UserStockEvaluateListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
