// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserIndexAddReader is a Reader for the UserIndexAdd structure.
type UserIndexAddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserIndexAddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserIndexAddOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserIndexAddBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUserIndexAddInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserIndexAddOK creates a UserIndexAddOK with default headers values
func NewUserIndexAddOK() *UserIndexAddOK {
	return &UserIndexAddOK{}
}

/*UserIndexAddOK handles this case with default header values.

ok
*/
type UserIndexAddOK struct {
	Payload *models.StockIndex
}

func (o *UserIndexAddOK) Error() string {
	return fmt.Sprintf("[PUT /{userId}/indices][%d] userIndexAddOK  %+v", 200, o.Payload)
}

func (o *UserIndexAddOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StockIndex)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserIndexAddBadRequest creates a UserIndexAddBadRequest with default headers values
func NewUserIndexAddBadRequest() *UserIndexAddBadRequest {
	return &UserIndexAddBadRequest{}
}

/*UserIndexAddBadRequest handles this case with default header values.

Bad request
*/
type UserIndexAddBadRequest struct {
	Payload string
}

func (o *UserIndexAddBadRequest) Error() string {
	return fmt.Sprintf("[PUT /{userId}/indices][%d] userIndexAddBadRequest  %+v", 400, o.Payload)
}

func (o *UserIndexAddBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserIndexAddInternalServerError creates a UserIndexAddInternalServerError with default headers values
func NewUserIndexAddInternalServerError() *UserIndexAddInternalServerError {
	return &UserIndexAddInternalServerError{}
}

/*UserIndexAddInternalServerError handles this case with default header values.

Internal error
*/
type UserIndexAddInternalServerError struct {
	Payload string
}

func (o *UserIndexAddInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /{userId}/indices][%d] userIndexAddInternalServerError  %+v", 500, o.Payload)
}

func (o *UserIndexAddInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
