// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserSettingsListParams creates a new UserSettingsListParams object
// with the default values initialized.
func NewUserSettingsListParams() *UserSettingsListParams {
	var ()
	return &UserSettingsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserSettingsListParamsWithTimeout creates a new UserSettingsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserSettingsListParamsWithTimeout(timeout time.Duration) *UserSettingsListParams {
	var ()
	return &UserSettingsListParams{

		timeout: timeout,
	}
}

// NewUserSettingsListParamsWithContext creates a new UserSettingsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserSettingsListParamsWithContext(ctx context.Context) *UserSettingsListParams {
	var ()
	return &UserSettingsListParams{

		Context: ctx,
	}
}

// NewUserSettingsListParamsWithHTTPClient creates a new UserSettingsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserSettingsListParamsWithHTTPClient(client *http.Client) *UserSettingsListParams {
	var ()
	return &UserSettingsListParams{
		HTTPClient: client,
	}
}

/*UserSettingsListParams contains all the parameters to send to the API endpoint
for the user settings list operation typically these are written to a http.Request
*/
type UserSettingsListParams struct {

	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user settings list params
func (o *UserSettingsListParams) WithTimeout(timeout time.Duration) *UserSettingsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user settings list params
func (o *UserSettingsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user settings list params
func (o *UserSettingsListParams) WithContext(ctx context.Context) *UserSettingsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user settings list params
func (o *UserSettingsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user settings list params
func (o *UserSettingsListParams) WithHTTPClient(client *http.Client) *UserSettingsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user settings list params
func (o *UserSettingsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the user settings list params
func (o *UserSettingsListParams) WithUserID(userID string) *UserSettingsListParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user settings list params
func (o *UserSettingsListParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserSettingsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
