// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserSettingsDeleteParams creates a new UserSettingsDeleteParams object
// with the default values initialized.
func NewUserSettingsDeleteParams() *UserSettingsDeleteParams {
	var ()
	return &UserSettingsDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserSettingsDeleteParamsWithTimeout creates a new UserSettingsDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserSettingsDeleteParamsWithTimeout(timeout time.Duration) *UserSettingsDeleteParams {
	var ()
	return &UserSettingsDeleteParams{

		timeout: timeout,
	}
}

// NewUserSettingsDeleteParamsWithContext creates a new UserSettingsDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserSettingsDeleteParamsWithContext(ctx context.Context) *UserSettingsDeleteParams {
	var ()
	return &UserSettingsDeleteParams{

		Context: ctx,
	}
}

// NewUserSettingsDeleteParamsWithHTTPClient creates a new UserSettingsDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserSettingsDeleteParamsWithHTTPClient(client *http.Client) *UserSettingsDeleteParams {
	var ()
	return &UserSettingsDeleteParams{
		HTTPClient: client,
	}
}

/*UserSettingsDeleteParams contains all the parameters to send to the API endpoint
for the user settings delete operation typically these are written to a http.Request
*/
type UserSettingsDeleteParams struct {

	/*ConfigKey
	  config key

	*/
	ConfigKey string
	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user settings delete params
func (o *UserSettingsDeleteParams) WithTimeout(timeout time.Duration) *UserSettingsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user settings delete params
func (o *UserSettingsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user settings delete params
func (o *UserSettingsDeleteParams) WithContext(ctx context.Context) *UserSettingsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user settings delete params
func (o *UserSettingsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user settings delete params
func (o *UserSettingsDeleteParams) WithHTTPClient(client *http.Client) *UserSettingsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user settings delete params
func (o *UserSettingsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigKey adds the configKey to the user settings delete params
func (o *UserSettingsDeleteParams) WithConfigKey(configKey string) *UserSettingsDeleteParams {
	o.SetConfigKey(configKey)
	return o
}

// SetConfigKey adds the configKey to the user settings delete params
func (o *UserSettingsDeleteParams) SetConfigKey(configKey string) {
	o.ConfigKey = configKey
}

// WithUserID adds the userID to the user settings delete params
func (o *UserSettingsDeleteParams) WithUserID(userID string) *UserSettingsDeleteParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user settings delete params
func (o *UserSettingsDeleteParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserSettingsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param configKey
	if err := r.SetPathParam("configKey", o.ConfigKey); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
