// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/NeuronEvolution/StockAssistant/api/models"
)

// UserSettingsListReader is a Reader for the UserSettingsList structure.
type UserSettingsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserSettingsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserSettingsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserSettingsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUserSettingsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserSettingsListOK creates a UserSettingsListOK with default headers values
func NewUserSettingsListOK() *UserSettingsListOK {
	return &UserSettingsListOK{}
}

/*UserSettingsListOK handles this case with default header values.

ok
*/
type UserSettingsListOK struct {
	Payload models.UserSettingsListOKBody
}

func (o *UserSettingsListOK) Error() string {
	return fmt.Sprintf("[GET /{userId}/settings][%d] userSettingsListOK  %+v", 200, o.Payload)
}

func (o *UserSettingsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserSettingsListBadRequest creates a UserSettingsListBadRequest with default headers values
func NewUserSettingsListBadRequest() *UserSettingsListBadRequest {
	return &UserSettingsListBadRequest{}
}

/*UserSettingsListBadRequest handles this case with default header values.

Bad request
*/
type UserSettingsListBadRequest struct {
	Payload string
}

func (o *UserSettingsListBadRequest) Error() string {
	return fmt.Sprintf("[GET /{userId}/settings][%d] userSettingsListBadRequest  %+v", 400, o.Payload)
}

func (o *UserSettingsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserSettingsListInternalServerError creates a UserSettingsListInternalServerError with default headers values
func NewUserSettingsListInternalServerError() *UserSettingsListInternalServerError {
	return &UserSettingsListInternalServerError{}
}

/*UserSettingsListInternalServerError handles this case with default header values.

Internal error
*/
type UserSettingsListInternalServerError struct {
	Payload string
}

func (o *UserSettingsListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{userId}/settings][%d] userSettingsListInternalServerError  %+v", 500, o.Payload)
}

func (o *UserSettingsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
