// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserSettingsGetParams creates a new UserSettingsGetParams object
// with the default values initialized.
func NewUserSettingsGetParams() *UserSettingsGetParams {
	var ()
	return &UserSettingsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserSettingsGetParamsWithTimeout creates a new UserSettingsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserSettingsGetParamsWithTimeout(timeout time.Duration) *UserSettingsGetParams {
	var ()
	return &UserSettingsGetParams{

		timeout: timeout,
	}
}

// NewUserSettingsGetParamsWithContext creates a new UserSettingsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserSettingsGetParamsWithContext(ctx context.Context) *UserSettingsGetParams {
	var ()
	return &UserSettingsGetParams{

		Context: ctx,
	}
}

// NewUserSettingsGetParamsWithHTTPClient creates a new UserSettingsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserSettingsGetParamsWithHTTPClient(client *http.Client) *UserSettingsGetParams {
	var ()
	return &UserSettingsGetParams{
		HTTPClient: client,
	}
}

/*UserSettingsGetParams contains all the parameters to send to the API endpoint
for the user settings get operation typically these are written to a http.Request
*/
type UserSettingsGetParams struct {

	/*ConfigKey
	  config key

	*/
	ConfigKey string
	/*UserID
	  User id

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user settings get params
func (o *UserSettingsGetParams) WithTimeout(timeout time.Duration) *UserSettingsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user settings get params
func (o *UserSettingsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user settings get params
func (o *UserSettingsGetParams) WithContext(ctx context.Context) *UserSettingsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user settings get params
func (o *UserSettingsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user settings get params
func (o *UserSettingsGetParams) WithHTTPClient(client *http.Client) *UserSettingsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user settings get params
func (o *UserSettingsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigKey adds the configKey to the user settings get params
func (o *UserSettingsGetParams) WithConfigKey(configKey string) *UserSettingsGetParams {
	o.SetConfigKey(configKey)
	return o
}

// SetConfigKey adds the configKey to the user settings get params
func (o *UserSettingsGetParams) SetConfigKey(configKey string) {
	o.ConfigKey = configKey
}

// WithUserID adds the userID to the user settings get params
func (o *UserSettingsGetParams) WithUserID(userID string) *UserSettingsGetParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user settings get params
func (o *UserSettingsGetParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserSettingsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param configKey
	if err := r.SetPathParam("configKey", o.ConfigKey); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
