// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserSettingsDeleteReader is a Reader for the UserSettingsDelete structure.
type UserSettingsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserSettingsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserSettingsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserSettingsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUserSettingsDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserSettingsDeleteOK creates a UserSettingsDeleteOK with default headers values
func NewUserSettingsDeleteOK() *UserSettingsDeleteOK {
	return &UserSettingsDeleteOK{}
}

/*UserSettingsDeleteOK handles this case with default header values.

ok
*/
type UserSettingsDeleteOK struct {
}

func (o *UserSettingsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /{userId}/settings/{configKey}][%d] userSettingsDeleteOK ", 200)
}

func (o *UserSettingsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUserSettingsDeleteBadRequest creates a UserSettingsDeleteBadRequest with default headers values
func NewUserSettingsDeleteBadRequest() *UserSettingsDeleteBadRequest {
	return &UserSettingsDeleteBadRequest{}
}

/*UserSettingsDeleteBadRequest handles this case with default header values.

Bad request
*/
type UserSettingsDeleteBadRequest struct {
	Payload string
}

func (o *UserSettingsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /{userId}/settings/{configKey}][%d] userSettingsDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *UserSettingsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserSettingsDeleteInternalServerError creates a UserSettingsDeleteInternalServerError with default headers values
func NewUserSettingsDeleteInternalServerError() *UserSettingsDeleteInternalServerError {
	return &UserSettingsDeleteInternalServerError{}
}

/*UserSettingsDeleteInternalServerError handles this case with default header values.

Internal error
*/
type UserSettingsDeleteInternalServerError struct {
	Payload string
}

func (o *UserSettingsDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /{userId}/settings/{configKey}][%d] userSettingsDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *UserSettingsDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
