// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IndexEvaluate index evaluate
// swagger:model IndexEvaluate

type IndexEvaluate struct {

	// eval remark
	EvalRemark string `json:"evalRemark,omitempty"`

	// eval stars
	EvalStars int32 `json:"evalStars,omitempty"`

	// index id
	IndexID string `json:"indexId,omitempty"`

	// update time
	UpdateTime strfmt.DateTime `json:"updateTime,omitempty"`
}

/* polymorph IndexEvaluate evalRemark false */

/* polymorph IndexEvaluate evalStars false */

/* polymorph IndexEvaluate indexId false */

/* polymorph IndexEvaluate updateTime false */

// Validate validates this index evaluate
func (m *IndexEvaluate) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IndexEvaluate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexEvaluate) UnmarshalBinary(b []byte) error {
	var res IndexEvaluate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
