// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StockIndex User stock index
// swagger:model StockIndex

type StockIndex struct {

	// ai weight
	AiWeight int32 `json:"aiWeight,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// Eval weight
	EvalWeight int32 `json:"evalWeight,omitempty"`

	// Id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// ni weight
	NiWeight int32 `json:"niWeight,omitempty"`
}

/* polymorph StockIndex aiWeight false */

/* polymorph StockIndex desc false */

/* polymorph StockIndex evalWeight false */

/* polymorph StockIndex id false */

/* polymorph StockIndex name false */

/* polymorph StockIndex niWeight false */

// Validate validates this stock index
func (m *StockIndex) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StockIndex) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StockIndex) UnmarshalBinary(b []byte) error {
	var res StockIndex
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
